from enum import Enum

class RejectedReason(Enum):
    HIGH_RISK = "HIGH_RISK"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    API_LIMIT = "API_LIMIT"
    BATTERY_LOW = "BATTERY_LOW"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"
    NO_PERMISSION = "NO_PERMISSION"
    TIMEOUT = "TIMEOUT"
    INSUFFICIENT_RESOURCE = "INSUFFICIENT_RESOURCE"